services:
  web01:
    build: 
      context: ./src-web
      dockerfile: Dockerfile
    container_name: web-LOCAL-01
    ports:
      - "4001:80"
    networks:
      - mi_red

  api:
    build:
      context: .
    container_name: api01
    ports:
      - "4002:8080"
    networks:
      - mi_red

  bd:
    image: postgres:15
    container_name: bd
    environment:
      POSTGRES_DB: mi_base_datos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
    ports:
      - "4003:5432"
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge